#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Font-TTF
Version  : 1.06
Release  : 29
URL      : https://cpan.metacpan.org/authors/id/B/BH/BHALLISSY/Font-TTF-1.06.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BH/BHALLISSY/Font-TTF-1.06.tar.gz
Summary  : 'TTF font support for Perl'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Font-TTF-license = %{version}-%{release}
Requires: perl-Font-TTF-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(IO::String)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=head1 INTRODUCTION
Perl module for TrueType/OpenType font hacking. Supports reading, processing and
writing of the following tables: GDEF, GPOS, GSUB, LTSH, OS/2, PCLT,
bsln, cmap, cvt, fdsc, feat, fpgm, glyf, hdmx, head, hhea, hmtx, kern,
loca, maxp, mort, name, post, prep, prop, vhea, vmtx and the reading and
writing of all other table types.

%package dev
Summary: dev components for the perl-Font-TTF package.
Group: Development
Provides: perl-Font-TTF-devel = %{version}-%{release}
Requires: perl-Font-TTF = %{version}-%{release}

%description dev
dev components for the perl-Font-TTF package.


%package license
Summary: license components for the perl-Font-TTF package.
Group: Default

%description license
license components for the perl-Font-TTF package.


%package perl
Summary: perl components for the perl-Font-TTF package.
Group: Default
Requires: perl-Font-TTF = %{version}-%{release}

%description perl
perl components for the perl-Font-TTF package.


%prep
%setup -q -n Font-TTF-1.06
cd %{_builddir}/Font-TTF-1.06

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Font-TTF
cp %{_builddir}/Font-TTF-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Font-TTF/09aa60e68ba922665fa60c4169d550aa34a94c2e || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Font::TTF.3
/usr/share/man/man3/Font::TTF::AATKern.3
/usr/share/man/man3/Font::TTF::AATutils.3
/usr/share/man/man3/Font::TTF::Anchor.3
/usr/share/man/man3/Font::TTF::Bsln.3
/usr/share/man/man3/Font::TTF::Cmap.3
/usr/share/man/man3/Font::TTF::Coverage.3
/usr/share/man/man3/Font::TTF::Cvt_.3
/usr/share/man/man3/Font::TTF::DSIG.3
/usr/share/man/man3/Font::TTF::Delta.3
/usr/share/man/man3/Font::TTF::Dumper.3
/usr/share/man/man3/Font::TTF::EBDT.3
/usr/share/man/man3/Font::TTF::EBLC.3
/usr/share/man/man3/Font::TTF::Fdsc.3
/usr/share/man/man3/Font::TTF::Feat.3
/usr/share/man/man3/Font::TTF::Features::Cvar.3
/usr/share/man/man3/Font::TTF::Features::Size.3
/usr/share/man/man3/Font::TTF::Features::Sset.3
/usr/share/man/man3/Font::TTF::Fmtx.3
/usr/share/man/man3/Font::TTF::Font.3
/usr/share/man/man3/Font::TTF::Fpgm.3
/usr/share/man/man3/Font::TTF::GDEF.3
/usr/share/man/man3/Font::TTF::GPOS.3
/usr/share/man/man3/Font::TTF::GSUB.3
/usr/share/man/man3/Font::TTF::Glat.3
/usr/share/man/man3/Font::TTF::Gloc.3
/usr/share/man/man3/Font::TTF::Glyf.3
/usr/share/man/man3/Font::TTF::Glyph.3
/usr/share/man/man3/Font::TTF::GrFeat.3
/usr/share/man/man3/Font::TTF::Hdmx.3
/usr/share/man/man3/Font::TTF::Head.3
/usr/share/man/man3/Font::TTF::Hhea.3
/usr/share/man/man3/Font::TTF::Hmtx.3
/usr/share/man/man3/Font::TTF::Kern.3
/usr/share/man/man3/Font::TTF::Kern::ClassArray.3
/usr/share/man/man3/Font::TTF::Kern::CompactClassArray.3
/usr/share/man/man3/Font::TTF::Kern::OrderedList.3
/usr/share/man/man3/Font::TTF::Kern::StateTable.3
/usr/share/man/man3/Font::TTF::Kern::Subtable.3
/usr/share/man/man3/Font::TTF::LTSH.3
/usr/share/man/man3/Font::TTF::Loca.3
/usr/share/man/man3/Font::TTF::Manual.3
/usr/share/man/man3/Font::TTF::Maxp.3
/usr/share/man/man3/Font::TTF::Mort.3
/usr/share/man/man3/Font::TTF::Mort::Chain.3
/usr/share/man/man3/Font::TTF::Mort::Contextual.3
/usr/share/man/man3/Font::TTF::Mort::Insertion.3
/usr/share/man/man3/Font::TTF::Mort::Ligature.3
/usr/share/man/man3/Font::TTF::Mort::Noncontextual.3
/usr/share/man/man3/Font::TTF::Mort::Rearrangement.3
/usr/share/man/man3/Font::TTF::Mort::Subtable.3
/usr/share/man/man3/Font::TTF::Name.3
/usr/share/man/man3/Font::TTF::OS_2.3
/usr/share/man/man3/Font::TTF::OTTags.3
/usr/share/man/man3/Font::TTF::OldCmap.3
/usr/share/man/man3/Font::TTF::OldMort.3
/usr/share/man/man3/Font::TTF::PCLT.3
/usr/share/man/man3/Font::TTF::PSNames.3
/usr/share/man/man3/Font::TTF::Post.3
/usr/share/man/man3/Font::TTF::Prep.3
/usr/share/man/man3/Font::TTF::Prop.3
/usr/share/man/man3/Font::TTF::Segarr.3
/usr/share/man/man3/Font::TTF::Silf.3
/usr/share/man/man3/Font::TTF::Sill.3
/usr/share/man/man3/Font::TTF::Table.3
/usr/share/man/man3/Font::TTF::Ttc.3
/usr/share/man/man3/Font::TTF::Ttopen.3
/usr/share/man/man3/Font::TTF::Useall.3
/usr/share/man/man3/Font::TTF::Utils.3
/usr/share/man/man3/Font::TTF::Vhea.3
/usr/share/man/man3/Font::TTF::Vmtx.3
/usr/share/man/man3/Font::TTF::Win32.3
/usr/share/man/man3/Font::TTF::Woff.3
/usr/share/man/man3/Font::TTF::Woff::MetaData.3
/usr/share/man/man3/Font::TTF::Woff::PrivateData.3
/usr/share/man/man3/Font::TTF::XMLparse.3
/usr/share/man/man3/ttfmod.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Font-TTF/09aa60e68ba922665fa60c4169d550aa34a94c2e

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
